
host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: 'rhel:8'
    operating_system:
      name: rhel
      version: "8.0"
    python_version: "3.6"
    recommendation_type: latest
    limit_latest_versions: 5

managers:
  - name: info
  - name: thoth-advise
    configuration:
      labels: [bot, kebechet]
<<<<<<< HEAD
=======
  - name: thoth-provenance
    configuration:
      labels: [bot, kebechet]
>>>>>>> 638ebb9d203c99cbbb96591ff8a3124ff1ffd81f
